package com.pack.tenderVO;
// default package
// Generated Aug 17, 2016 5:12:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.siservices.signup.persistense.UserMasterTblVo;
import com.siservices.uam.persistense.SocietyMstTbl;

/**
 * MvpTenderDocTbl generated by hbm2java
 */
public class TenderDocTblVO implements java.io.Serializable {

	private Integer tenderDocId;
	private SocietyMstTbl societyMstTbl;
	private UserMasterTblVo usrRegTbl;
	private TenderTblVO mvpTenderTbl;
	private String documentName;
	private String documentType;
	private Integer entryBy;
	private Date entryDatetime;
	private Date modifyDatetime;
	private Integer ivrBnSTATUS;
	public TenderDocTblVO() {
	}

	public TenderDocTblVO(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	/*public TenderDocTblVO(SocietyMstTbl societyMstTbl, UsrRegTbl usrRegTbl,
			MvpTenderTbl mvpTenderTbl, String documentName,
			String documentType, Integer entryBy, Date entryDatetime,
			Date modifyDatetime) {
		this.societyMstTbl = societyMstTbl;
		this.usrRegTbl = usrRegTbl;
		this.mvpTenderTbl = mvpTenderTbl;
		this.documentName = documentName;
		this.documentType = documentType;
		this.entryBy = entryBy;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}*/

	public Integer getTenderDocId() {
		return this.tenderDocId;
	}

	public void setTenderDocId(Integer tenderDocId) {
		this.tenderDocId = tenderDocId;
	}

	public SocietyMstTbl getSocietyMstTbl() {
		return this.societyMstTbl;
	}

	public void setSocietyMstTbl(SocietyMstTbl societyMstTbl) {
		this.societyMstTbl = societyMstTbl;
	}

	

	public UserMasterTblVo getUsrRegTbl() {
		return usrRegTbl;
	}

	public void setUsrRegTbl(UserMasterTblVo usrRegTbl) {
		this.usrRegTbl = usrRegTbl;
	}

	public TenderTblVO getMvpTenderTbl() {
		return mvpTenderTbl;
	}

	public void setMvpTenderTbl(TenderTblVO mvpTenderTbl) {
		this.mvpTenderTbl = mvpTenderTbl;
	}

	public String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getIvrBnSTATUS() {
		return ivrBnSTATUS;
	}

	public void setIvrBnSTATUS(Integer ivrBnSTATUS) {
		this.ivrBnSTATUS = ivrBnSTATUS;
	}

	
	

}
