package com.pack.tenderVO;
// default package
// Generated Aug 17, 2016 5:12:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.siservices.signup.persistense.UserMasterTblVo;
import com.siservices.uam.persistense.GroupMasterTblVo;

/**
 * MvpTenderTbl generated by hbm2java
 */
public class TenderTblVO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer tenderId;
	private UserMasterTblVo usrRegTbl;
	private GroupMasterTblVo groupMstTbl;
	private String tenderName;
	private String tenderDate;
	private Float tenderAmount;
	private String tenderDetails;
	private Integer entryBy;
	private Date entryDatetime;
	private Date modyDatetime;
	private Integer ivrBnSTATUS;

	public TenderTblVO() {
	}

	public TenderTblVO(Date modyDatetime) {
		this.modyDatetime = modyDatetime;
	}

	public TenderTblVO(UserMasterTblVo usrRegTbl, GroupMasterTblVo groupMstTbl,
			String tenderName, String tenderDate, Float tenderAmount,
			String tenderDetails, Integer entryBy, Date entryDatetime,
			Date modyDatetime) {
		this.usrRegTbl = usrRegTbl;
		this.groupMstTbl = groupMstTbl;
		this.tenderName = tenderName;
		this.tenderDate = tenderDate;
		this.tenderAmount = tenderAmount;
		this.tenderDetails = tenderDetails;
		this.entryBy = entryBy;
		this.entryDatetime = entryDatetime;
		this.modyDatetime = modyDatetime;
		
	}

	public Integer getTenderId() {
		return this.tenderId;
	}

	public void setTenderId(Integer tenderId) {
		this.tenderId = tenderId;
	}

	

	public UserMasterTblVo getUsrRegTbl() {
		return usrRegTbl;
	}

	public void setUsrRegTbl(UserMasterTblVo usrRegTbl) {
		this.usrRegTbl = usrRegTbl;
	}

	public GroupMasterTblVo getGroupMstTbl() {
		return groupMstTbl;
	}

	public void setGroupMstTbl(GroupMasterTblVo groupMstTbl) {
		this.groupMstTbl = groupMstTbl;
	}

	public String getTenderName() {
		return this.tenderName;
	}

	public void setTenderName(String tenderName) {
		this.tenderName = tenderName;
	}

	public String getTenderDate() {
		return tenderDate;
	}

	public void setTenderDate(String tenderDate) {
		this.tenderDate = tenderDate;
	}

	public Float getTenderAmount() {
		return this.tenderAmount;
	}

	public void setTenderAmount(Float tenderAmount) {
		this.tenderAmount = tenderAmount;
	}

	public String getTenderDetails() {
		return this.tenderDetails;
	}

	public void setTenderDetails(String tenderDetails) {
		this.tenderDetails = tenderDetails;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModyDatetime() {
		return this.modyDatetime;
	}

	public void setModyDatetime(Date modyDatetime) {
		this.modyDatetime = modyDatetime;
	}

	public Integer getIvrBnSTATUS() {
		return ivrBnSTATUS;
	}

	public void setIvrBnSTATUS(Integer ivrBnSTATUS) {
		this.ivrBnSTATUS = ivrBnSTATUS;
	}

	
	

}
