package com.socialindiaservices.vo;
// default package
// Generated Jan 5, 2017 11:25:36 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MvpDonationCategoryMstTbl generated by hbm2java
 */
public class MvpDonationCategoryMstTbl implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer categoryId;
	private String categoryName;
	private String categoryShrtForm;
	private String categoryDesc;
	private Integer categoryFlag;
	private Integer categoryType;
	private String categoryImage;
	private Integer status;
	private Integer entryBy;
	private Date entryDate;
	private Date modifyDate;

	public MvpDonationCategoryMstTbl() {
	}

	public MvpDonationCategoryMstTbl(Date modifyDate) {
		this.modifyDate = modifyDate;
	}



	public String getCategoryShrtForm() {
		return categoryShrtForm;
	}

	public void setCategoryShrtForm(String categoryShrtForm) {
		this.categoryShrtForm = categoryShrtForm;
	}

	public String getCategoryDesc() {
		return categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	public Integer getCategoryFlag() {
		return categoryFlag;
	}

	public void setCategoryFlag(Integer categoryFlag) {
		this.categoryFlag = categoryFlag;
	}

	public Integer getCategoryType() {
		return categoryType;
	}

	public void setCategoryType(Integer categoryType) {
		this.categoryType = categoryType;
	}

	public String getCategoryImage() {
		return categoryImage;
	}

	public void setCategoryImage(String categoryImage) {
		this.categoryImage = categoryImage;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}



}
