package com.socialindiaservices.vo;

// default package
// Generated Dec 8, 2016 4:01:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.siservices.signup.persistense.UserMasterTblVo;

/**
 * MvpEvotingMstTbl generated by hbm2java
 */
public class MvpEvotingMstTbl implements java.io.Serializable {

	private Integer evotingId;
	private UserMasterTblVo usrRegTbl;
	private String titile;
	private String description;
	private Integer statusFlag;
	private Integer publishFlag;
	private Date entryDatetime;
	private Date modifyDatetime;
	private UserMasterTblVo modifyBy;

	public MvpEvotingMstTbl() {
	}

	public MvpEvotingMstTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public MvpEvotingMstTbl(UserMasterTblVo usrRegTbl, String titile,
			String description, Integer statusFlag,
			Integer publishFlag, Date entryDatetime, Date modifyDatetime,
			UserMasterTblVo modifyBy) {
		this.usrRegTbl = usrRegTbl;
		this.titile = titile;
		this.description = description;
		this.statusFlag = statusFlag;
		this.publishFlag = publishFlag;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
		this.modifyBy = modifyBy;
	}

	public Integer getEvotingId() {
		return this.evotingId;
	}

	public void setEvotingId(Integer evotingId) {
		this.evotingId = evotingId;
	}

	public UserMasterTblVo getUsrRegTbl() {
		return this.usrRegTbl;
	}

	public void setUsrRegTbl(UserMasterTblVo usrRegTbl) {
		this.usrRegTbl = usrRegTbl;
	}

	public String getTitile() {
		return this.titile;
	}

	public void setTitile(String titile) {
		this.titile = titile;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	public Integer getStatusFlag() {
		return this.statusFlag;
	}

	public void setStatusFlag(Integer statusFlag) {
		this.statusFlag = statusFlag;
	}

	public Integer getPublishFlag() {
		return this.publishFlag;
	}

	public void setPublishFlag(Integer publishFlag) {
		this.publishFlag = publishFlag;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public UserMasterTblVo getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(UserMasterTblVo modifyBy) {
		this.modifyBy = modifyBy;
	}

}
