package com.socialindiaservices.vo;
// default package
// Generated Dec 9, 2016 3:43:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MvpEvotingImageTbl generated by hbm2java
 */
public class MvpEvotingImageTbl implements java.io.Serializable {

	private Integer evotingImageId; 
	private MvpEvotingMstTbl mvpEvotingMstTbl;
	private String imageName;
	private String thumpImage;
	private int fileType;
	private int statusFlag;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpEvotingImageTbl() {
	}

	public MvpEvotingImageTbl(MvpEvotingMstTbl mvpEvotingMstTbl,
			String imageName, int statusFlag, Date entryDatetime,
			Date modifyDatetime) {
		this.mvpEvotingMstTbl = mvpEvotingMstTbl;
		this.imageName = imageName;
		this.statusFlag = statusFlag;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getEvotingImageId() {
		return this.evotingImageId;
	}

	public void setEvotingImageId(Integer evotingImageId) {
		this.evotingImageId = evotingImageId;
	}

	public MvpEvotingMstTbl getMvpEvotingMstTbl() {
		return this.mvpEvotingMstTbl;
	}

	public void setMvpEvotingMstTbl(MvpEvotingMstTbl mvpEvotingMstTbl) {
		this.mvpEvotingMstTbl = mvpEvotingMstTbl;
	}

	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	public String getThumpImage() {
		return thumpImage;
	}

	public void setThumpImage(String thumpImage) {
		this.thumpImage = thumpImage;
	}

	public int getFileType() {
		return fileType;
	}

	public void setFileType(int fileType) {
		this.fileType = fileType;
	}

	public int getStatusFlag() {
		return this.statusFlag;
	}

	public void setStatusFlag(int statusFlag) {
		this.statusFlag = statusFlag;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

}
