// default package
// Generated Dec 29, 2016 12:05:11 PM by Hibernate Tools 3.4.0.CR1
package com.socialindiaservices.vo;


import java.util.Date;

import com.siservices.signup.persistense.UserMasterTblVo;

/**
 * MvpFavouriteTbl generated by hbm2java
 */
public class MvpFavouriteTbl implements java.io.Serializable {

	private Integer favouriteId;
	private UserMasterTblVo usrRegTbl;
	private Integer favouriteType;
	private Integer favouriteTypeId;
	private Integer status;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpFavouriteTbl() {
	}

	public MvpFavouriteTbl(UserMasterTblVo usrRegTbl, Integer favouriteType,
			Integer favouriteTypeId, Integer status, Date entryDatetime,
			Date modifyDatetime) {
		this.usrRegTbl = usrRegTbl;
		this.favouriteType = favouriteType;
		this.favouriteTypeId = favouriteTypeId;
		this.status = status;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getFavouriteId() {
		return this.favouriteId;
	}

	public void setFavouriteId(Integer favouriteId) {
		this.favouriteId = favouriteId;
	}

	public UserMasterTblVo getUsrRegTbl() {
		return this.usrRegTbl;
	}

	public void setUsrRegTbl(UserMasterTblVo usrRegTbl) {
		this.usrRegTbl = usrRegTbl;
	}

	public Integer getFavouriteType() {
		return this.favouriteType;
	}

	public void setFavouriteType(Integer favouriteType) {
		this.favouriteType = favouriteType;
	}

	public Integer getFavouriteTypeId() {
		return this.favouriteTypeId;
	}

	public void setFavouriteTypeId(Integer favouriteTypeId) {
		this.favouriteTypeId = favouriteTypeId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

}
