package com.mobi.easypayvo;

import java.util.Date;

/**
 * MvpExternalOperatorConfigTbl generated by hbm2java
 */
public class MvpExternalOperatorConfigTbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer extranalId;
	private String extranalKey;
	private String extranalValue;
	private Integer status;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpExternalOperatorConfigTbl() {
	}

	public Integer getExtranalId() {
		return this.extranalId;
	}

	public void setExtranalId(Integer extranalId) {
		this.extranalId = extranalId;
	}

	public String getExtranalKey() {
		return this.extranalKey;
	}

	public void setExtranalKey(String extranalKey) {
		this.extranalKey = extranalKey;
	}

	public String getExtranalValue() {
		return this.extranalValue;
	}

	public void setExtranalValue(String extranalValue) {
		this.extranalValue = extranalValue;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

}
