package com.mobi.easypayvo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MvpUtilityPayTbl generated by hbm2java
 */
public class MvpUtilityPayTbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer utilityPayId;
	private String sd;
	private String ap;
	private String op;
	private String session;
	private String number;
	private Float amount;
	private String amountAll;
	private String comment;
	private String termId;
	private String authenticator3;
	private String date;
	private String error;
	private String result;
	private String transid;
	private String phonenumber;
	private String circle;
	private String account;
	private String authcode;
	private String addinfo;
	private String price;
	private String billdate;
	private String billnumber;
	private String errmsg;
	private String trnxstatus;
	private Integer finalStatus;
	private int usrId;
	private Integer operatorCodeId;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpUtilityPayTbl() {
	}


	public Integer getUtilityPayId() {
		return this.utilityPayId;
	}

	public void setUtilityPayId(Integer utilityPayId) {
		this.utilityPayId = utilityPayId;
	}

	public String getSd() {
		return this.sd;
	}

	public void setSd(String sd) {
		this.sd = sd;
	}

	public String getAp() {
		return this.ap;
	}

	public void setAp(String ap) {
		this.ap = ap;
	}

	public String getOp() {
		return this.op;
	}

	public void setOp(String op) {
		this.op = op;
	}

	public String getSession() {
		return session;
	}

	public void setSession(String session) {
		this.session = session;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Float getAmount() {
		return amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public String getAmountAll() {
		return this.amountAll;
	}

	public void setAmountAll(String amountAll) {
		this.amountAll = amountAll;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getTermId() {
		return this.termId;
	}

	public void setTermId(String termId) {
		this.termId = termId;
	}

	public String getAuthenticator3() {
		return this.authenticator3;
	}

	public void setAuthenticator3(String authenticator3) {
		this.authenticator3 = authenticator3;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getTransid() {
		return this.transid;
	}

	public void setTransid(String transid) {
		this.transid = transid;
	}

	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	public String getCircle() {
		return this.circle;
	}

	public void setCircle(String circle) {
		this.circle = circle;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getAuthcode() {
		return this.authcode;
	}

	public void setAuthcode(String authcode) {
		this.authcode = authcode;
	}

	public String getAddinfo() {
		return this.addinfo;
	}

	public void setAddinfo(String addinfo) {
		this.addinfo = addinfo;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getBilldate() {
		return this.billdate;
	}

	public void setBilldate(String billdate) {
		this.billdate = billdate;
	}

	public String getBillnumber() {
		return this.billnumber;
	}

	public void setBillnumber(String billnumber) {
		this.billnumber = billnumber;
	}

	public String getErrmsg() {
		return this.errmsg;
	}

	public void setErrmsg(String errmsg) {
		this.errmsg = errmsg;
	}

	public String getTrnxstatus() {
		return this.trnxstatus;
	}

	public void setTrnxstatus(String trnxstatus) {
		this.trnxstatus = trnxstatus;
	}

	public Integer getFinalStatus() {
		return this.finalStatus;
	}

	public void setFinalStatus(Integer finalStatus) {
		this.finalStatus = finalStatus;
	}

	public int getUsrId() {
		return this.usrId;
	}

	public void setUsrId(int usrId) {
		this.usrId = usrId;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getOperatorCodeId() {
		return operatorCodeId;
	}

	public void setOperatorCodeId(Integer operatorCodeId) {
		this.operatorCodeId = operatorCodeId;
	}
	

}
