package com.mobi.addpost;

// default package
// Generated Sep 30, 2016 11:47:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.pack.commonvo.CategoryMasterTblVO;
import com.pack.commonvo.SkillMasterTblVO;
import com.siservices.signup.persistense.UserMasterTblVo;

/**
 * MvpAdpostTbl generated by hbm2java
 */
public class MvpAdpostTbl implements java.io.Serializable {

	private Integer postUniqueId;
	private SkillMasterTblVO ivrBnSKILL_ID;
	private UserMasterTblVo userId;
	private CategoryMasterTblVO iVOCATEGORY_ID;
	private String postTitle;
	private String shortDesc;
	private String descr;
	private String contactNo;
	private Float price;
	private Integer buyerSellerFlag;
	private Integer feedId;
	private Integer actSts;
	private Integer entryBy;
	private Date entryDatetime;
	private Date modifyDatetime;
	

	public MvpAdpostTbl() {
	}

	public MvpAdpostTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public MvpAdpostTbl(SkillMasterTblVO mvpSkillTbl, UserMasterTblVo usrRegTbl,
			CategoryMasterTblVO categoryMstTbl, String postTitle, String shortDesc,
			String descr, String contactNo, Integer quantity, Float price,
			String imgName, String embedVideoUrl, Integer unsedNewFlg,
			Integer modifyFlg, Integer actSts, Integer entryBy,
			Date entryDatetime, Date modifyDatetime) {
		this.ivrBnSKILL_ID = mvpSkillTbl;
		this.userId = usrRegTbl;
		this.iVOCATEGORY_ID = categoryMstTbl;
		this.postTitle = postTitle;
		this.shortDesc = shortDesc;
		this.descr = descr;
		this.contactNo = contactNo;
		this.price = price;
		this.actSts = actSts;
		this.entryBy = entryBy;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public SkillMasterTblVO getIvrBnSKILL_ID() {
		return ivrBnSKILL_ID;
	}

	public void setIvrBnSKILL_ID(SkillMasterTblVO ivrBnSKILL_ID) {
		this.ivrBnSKILL_ID = ivrBnSKILL_ID;
	}

	public UserMasterTblVo getUserId() {
		return userId;
	}

	public void setUserId(UserMasterTblVo userId) {
		this.userId = userId;
	}

	public CategoryMasterTblVO getiVOCATEGORY_ID() {
		return iVOCATEGORY_ID;
	}

	public void setiVOCATEGORY_ID(CategoryMasterTblVO iVOCATEGORY_ID) {
		this.iVOCATEGORY_ID = iVOCATEGORY_ID;
	}

	public Integer getPostUniqueId() {
		return this.postUniqueId;
	}

	public void setPostUniqueId(Integer postUniqueId) {
		this.postUniqueId = postUniqueId;
	}

	

	public String getPostTitle() {
		return this.postTitle;
	}

	public void setPostTitle(String postTitle) {
		this.postTitle = postTitle;
	}

	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	

	public Integer getActSts() {
		return this.actSts;
	}

	public void setActSts(Integer actSts) {
		this.actSts = actSts;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getBuyerSellerFlag() {
		return buyerSellerFlag;
	}

	public void setBuyerSellerFlag(Integer buyerSellerFlag) {
		this.buyerSellerFlag = buyerSellerFlag;
	}

	public Integer getFeedId() {
		return feedId;
	}

	public void setFeedId(Integer feedId) {
		this.feedId = feedId;
	}

	

}
