package com.pack.complaintVO;

import java.util.Date;

import org.jsmpp.bean.OptionalParameter.Int;

import com.pack.timelinefeedvo.FeedsTblVO;
import com.siservices.signup.persistense.UserMasterTblVo;
import com.siservices.uam.persistense.GroupMasterTblVo;
import com.siservices.uam.persistense.SocietyMstTbl;

/**
 * MvpComplaintsTbl generated by hbm2java
 */
public class ComplaintsTblVO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer complaintsId;
	private UserMasterTblVo usrRegTblByFromUsrId;
	private GroupMasterTblVo groupMstTblByFromGroupId;
	private Integer groupMstTblByToGroupId;
	private Integer usrRegTblByToUsrId;
	private String complaintsTitle;
	private String complaintsDesc;
	private String complaintsFileName1;
	private String complaintsFileName2;
	private String complaintsFileName3;
	private String videoPath;
	private String complaintsOthersEmail;
	private Integer status;
	private Integer entryBy;
	private Integer complaintsCompleteBy;
	private Date entryDatetime;
	private Date modifyDatetime;
	private String closereason;
	private String ShrtDesc;
	private Integer compliantsToFlag;
	
	private Integer feedId;
	
	
	

	public ComplaintsTblVO() {
	}

	public ComplaintsTblVO(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	/*public ComplaintsTblVO(UserMasterTblVo usrRegTblByFromUsrId,
			GroupMasterTblVo groupMstTblByToGroupId,
			GroupMasterTblVo groupMstTblByFromGroupId, UserMasterTblVo usrRegTblByToUsrId,
			String complaintsTitle, String complaintsDesc,
			String complaintsFileName, String videoPath,
			String complaintsOthersEmail, Integer status, Integer entryBy,
			Integer complaintsCompleteBy, Date entryDatetime,
			Date modifyDatetime) {
		this.usrRegTblByFromUsrId = usrRegTblByFromUsrId;
		this.groupMstTblByToGroupId = groupMstTblByToGroupId;
		this.groupMstTblByFromGroupId = groupMstTblByFromGroupId;
		this.usrRegTblByToUsrId = usrRegTblByToUsrId;
		this.complaintsTitle = complaintsTitle;
		this.complaintsDesc = complaintsDesc;
		this.complaintsFileName = complaintsFileName;
		this.videoPath = videoPath;
		this.complaintsOthersEmail = complaintsOthersEmail;
		this.status = status;
		this.entryBy = entryBy;
		this.complaintsCompleteBy = complaintsCompleteBy;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}*/

	public String getShrtDesc() {
		return ShrtDesc;
	}

	public void setShrtDesc(String shrtDesc) {
		ShrtDesc = shrtDesc;
	}

	public Integer getComplaintsId() {
		return this.complaintsId;
	}

	public void setComplaintsId(Integer complaintsId) {
		this.complaintsId = complaintsId;
	}

	

	

	public Integer getCompliantsToFlag() {
		return compliantsToFlag;
	}

	public void setCompliantsToFlag(Integer compliantsToFlag) {
		this.compliantsToFlag = compliantsToFlag;
	}

	public UserMasterTblVo getUsrRegTblByFromUsrId() {
		return usrRegTblByFromUsrId;
	}

	public void setUsrRegTblByFromUsrId(UserMasterTblVo usrRegTblByFromUsrId) {
		this.usrRegTblByFromUsrId = usrRegTblByFromUsrId;
	}

	

	public GroupMasterTblVo getGroupMstTblByFromGroupId() {
		return groupMstTblByFromGroupId;
	}

	public void setGroupMstTblByFromGroupId(
			GroupMasterTblVo groupMstTblByFromGroupId) {
		this.groupMstTblByFromGroupId = groupMstTblByFromGroupId;
	}

	

	public Integer getGroupMstTblByToGroupId() {
		return groupMstTblByToGroupId;
	}

	public void setGroupMstTblByToGroupId(Integer groupMstTblByToGroupId) {
		this.groupMstTblByToGroupId = groupMstTblByToGroupId;
	}

	public Integer getUsrRegTblByToUsrId() {
		return usrRegTblByToUsrId;
	}

	public void setUsrRegTblByToUsrId(Integer usrRegTblByToUsrId) {
		this.usrRegTblByToUsrId = usrRegTblByToUsrId;
	}

	public String getComplaintsTitle() {
		return this.complaintsTitle;
	}

	public void setComplaintsTitle(String complaintsTitle) {
		this.complaintsTitle = complaintsTitle;
	}

	public String getComplaintsDesc() {
		return this.complaintsDesc;
	}

	public void setComplaintsDesc(String complaintsDesc) {
		this.complaintsDesc = complaintsDesc;
	}

	

	public String getComplaintsFileName1() {
		return complaintsFileName1;
	}

	public void setComplaintsFileName1(String complaintsFileName1) {
		this.complaintsFileName1 = complaintsFileName1;
	}

	public String getComplaintsFileName2() {
		return complaintsFileName2;
	}

	public void setComplaintsFileName2(String complaintsFileName2) {
		this.complaintsFileName2 = complaintsFileName2;
	}

	public String getComplaintsFileName3() {
		return complaintsFileName3;
	}

	public void setComplaintsFileName3(String complaintsFileName3) {
		this.complaintsFileName3 = complaintsFileName3;
	}

	public String getVideoPath() {
		return this.videoPath;
	}

	public void setVideoPath(String videoPath) {
		this.videoPath = videoPath;
	}

	public String getComplaintsOthersEmail() {
		return this.complaintsOthersEmail;
	}

	public void setComplaintsOthersEmail(String complaintsOthersEmail) {
		this.complaintsOthersEmail = complaintsOthersEmail;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Integer getComplaintsCompleteBy() {
		return this.complaintsCompleteBy;
	}

	public void setComplaintsCompleteBy(Integer complaintsCompleteBy) {
		this.complaintsCompleteBy = complaintsCompleteBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getClosereason() {
		return closereason;
	}

	public void setClosereason(String closereason) {
		this.closereason = closereason;
	}

	public Integer getFeedId() {
		return feedId;
	}

	public void setFeedId(Integer feedId) {
		this.feedId = feedId;
	}
	

}
