package com.siservices.uam.persistense;

// default package
// Generated Jun 14, 2016 2:48:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.pack.commonvo.CityMasterTblVO;
import com.pack.commonvo.CountryMasterTblVO;
import com.pack.commonvo.PostalCodeMasterTblVO;
import com.pack.commonvo.StateMasterTblVO;

/**
 * TownshipMstTbl generated by hbm2java
 */
public class TownshipMstTbl implements java.io.Serializable {

	private Integer townshipId;
	private String activationKey;
	private StateMasterTblVO stateId;
	private CityMasterTblVO cityId;
	private CountryMasterTblVO countryId;
//	private PostalCodeMasterTblVO pstlId;
	private Integer pstlId;
	private String townshipUniqueId;
	private String townshiplogoname;
	private String townshipiconame;
	private String townshipcolourcode;
	private String townshipName;
	private int noOfSociety;
	private int noOfFlats;
	private String address;
	
	private String oldActivationKey;
	private String builderName;
	private String emailId;
	private String isdCode;
	private String mobileNo;
	private String landMark;
	private String imprintName;
	private Integer entryby;
	private Date entryDatetime;
	private Date modifyDatetime; 
	private int status;

	public TownshipMstTbl() {
	}

	public TownshipMstTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public TownshipMstTbl(Integer townshipId,StateMasterTblVO stateId, CityMasterTblVO cityId,
			CountryMasterTblVO countryId, String townshiplogoname,String townshipiconame,
			String townshipcolourcode, String townshipUniqueId,
			String townshipName, Integer entryby, Date entryDatetime,
			Date modifyDatetime,int status ) {
		this.townshipId = townshipId;
		this.stateId = stateId;
		this.cityId = cityId;
		this.countryId = countryId;
		this.townshipUniqueId = townshipUniqueId;
		this.townshipName = townshipName;
		this.townshiplogoname = townshiplogoname;
		this.townshipiconame = townshipiconame;
		this.townshipcolourcode = townshipcolourcode;
		this.entryby = entryby;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
		this.status=status;
	}

	public Integer getTownshipId() {
		return this.townshipId;
	}

	public void setTownshipId(Integer townshipId) {
		this.townshipId = townshipId;
	}

	public StateMasterTblVO getStateId() {
		return stateId;
	}

	public void setStateId(StateMasterTblVO stateId) {
		this.stateId = stateId;
	}

	public CityMasterTblVO getCityId() {
		return cityId;
	}

	public void setCityId(CityMasterTblVO cityId) {
		this.cityId = cityId;
	}

	public CountryMasterTblVO getCountryId() {
		return countryId;
	}

	public void setCountryId(CountryMasterTblVO countryId) {
		this.countryId = countryId;
	}

	public String getTownshipUniqueId() {
		return this.townshipUniqueId;
	}

	public void setTownshipUniqueId(String townshipUniqueId) {
		this.townshipUniqueId = townshipUniqueId;
	}

	public String getTownshipName() {
		return this.townshipName;
	}

	public void setTownshipName(String townshipName) {
		this.townshipName = townshipName;
	}

	public Integer getEntryby() {
		return this.entryby;
	}

	public void setEntryby(Integer entryby) {
		this.entryby = entryby;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getTownshiplogoname() {
		return townshiplogoname;
	}

	public void setTownshiplogoname(String townshiplogoname) {
		this.townshiplogoname = townshiplogoname;
	}

	public String getTownshipiconame() {
		return townshipiconame;
	}

	public void setTownshipiconame(String townshipiconame) {
		this.townshipiconame = townshipiconame;
	}

	public String getTownshipcolourcode() {
		return townshipcolourcode;
	}

	public void setTownshipcolourcode(String townshipcolourcode) {
		this.townshipcolourcode = townshipcolourcode;
	}

	public String getActivationKey() {
		return activationKey;
	}

	public void setActivationKey(String activationKey) {
		this.activationKey = activationKey;
	}

	public int getNoOfSociety() {
		return noOfSociety;
	}

	public void setNoOfSociety(int noOfSociety) {
		this.noOfSociety = noOfSociety;
	}

	public int getNoOfFlats() {
		return noOfFlats;
	}

	public void setNoOfFlats(int noOfFlats) {
		this.noOfFlats = noOfFlats;
	}

//	public PostalCodeMasterTblVO getPstlId() {
//		return pstlId;
//	}
//
//	public void setPstlId(PostalCodeMasterTblVO pstlId) {
//		this.pstlId = pstlId;
//	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getBuilderName() {
		return builderName;
	}

	public void setBuilderName(String builderName) {
		this.builderName = builderName;
	}

	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getIsdCode() {
		return isdCode;
	}

	public void setIsdCode(String isdCode) {
		this.isdCode = isdCode;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getLandMark() {
		return landMark;
	}

	public void setLandMark(String landMark) {
		this.landMark = landMark;
	}

	public String getImprintName() {
		return imprintName;
	}

	public void setImprintName(String imprintName) {
		this.imprintName = imprintName;
	}

	public String getOldActivationKey() {
		return oldActivationKey;
	}

	public void setOldActivationKey(String oldActivationKey) {
		this.oldActivationKey = oldActivationKey;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Integer getPstlId() {
		return pstlId;
	}

	public void setPstlId(Integer pstlId) {
		this.pstlId = pstlId;
	}
	

}
