package com.mobi.addpost;

// default package
// Generated Oct 10, 2016 1:28:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MvpAdpostAttchTbl generated by hbm2java
 */
public class MvpAdpostAttchTbl implements java.io.Serializable {

	private Integer adpostAttchId;
	private MvpAdpostTbl postUniqueId;
	private String attachName;
	private Integer status;
	private String thumbImage;
	private Integer ivrBnFILE_TYPE;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpAdpostAttchTbl() {
	}

	public MvpAdpostAttchTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public MvpAdpostAttchTbl(MvpAdpostTbl mvpAdpostTbl, String attachName,
			Integer status, Date entryDatetime, Date modifyDatetime) {
		this.postUniqueId = mvpAdpostTbl;
		this.attachName = attachName;
		this.status = status;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getAdpostAttchId() {
		return this.adpostAttchId;
	}

	public void setAdpostAttchId(Integer adpostAttchId) {
		this.adpostAttchId = adpostAttchId;
	}

	

	public MvpAdpostTbl getPostUniqueId() {
		return postUniqueId;
	}

	public void setPostUniqueId(MvpAdpostTbl postUniqueId) {
		this.postUniqueId = postUniqueId;
	}

	public String getAttachName() {
		return this.attachName;
	}

	public void setAttachName(String attachName) {
		this.attachName = attachName;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getThumbImage() {
		return thumbImage;
	}

	public void setThumbImage(String thumbImage) {
		this.thumbImage = thumbImage;
	}

	public Integer getIvrBnFILE_TYPE() {
		return ivrBnFILE_TYPE;
	}

	public void setIvrBnFILE_TYPE(Integer ivrBnFILE_TYPE) {
		this.ivrBnFILE_TYPE = ivrBnFILE_TYPE;
	}

}
