package com.mobi.easypayvo;

import java.util.Date;

/**
 * MvpPaygateTbl generated by hbm2java
 */
public class MvpPaygateTbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer paygateId;
	private String agId;
	private String meId;
	private String orderNo;
	private Float amount;
	private String country;
	private String currency;
	private String txnType;
	private String successUrl;
	private String failureUrl;
	private String channel;
	private String txnDate;
	private String txnTime;
	private String agRef;
	private String pgRef;
	private String status;
	private String resCode;
	private String resMessage;
	private Integer finalStatus;
	private String txnResponse;
	private String pgDetails;
	private String fraudDetails;
	private String otherDetails;
	private String cardDetails;
	private String custDetails;
	private String billDetails;
	private String shipDetails;
	private String itemDetails;
	private String otherDetail;
	private int usrId;
	private String udf_1Data;
	private String udf_2Data;
	private String udf_3Data;
	private String udf_4Data;
	private String udf_5Data;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpPaygateTbl() {
	}

	public Integer getPaygateId() {
		return this.paygateId;
	}

	public void setPaygateId(Integer paygateId) {
		this.paygateId = paygateId;
	}

	public String getAgId() {
		return this.agId;
	}

	public void setAgId(String agId) {
		this.agId = agId;
	}

	public String getMeId() {
		return this.meId;
	}

	public void setMeId(String meId) {
		this.meId = meId;
	}

	public String getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	public String getSuccessUrl() {
		return this.successUrl;
	}

	public void setSuccessUrl(String successUrl) {
		this.successUrl = successUrl;
	}

	public String getFailureUrl() {
		return this.failureUrl;
	}

	public void setFailureUrl(String failureUrl) {
		this.failureUrl = failureUrl;
	}

	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(String txnDate) {
		this.txnDate = txnDate;
	}

	public String getTxnTime() {
		return this.txnTime;
	}

	public void setTxnTime(String txnTime) {
		this.txnTime = txnTime;
	}

	public String getAgRef() {
		return this.agRef;
	}

	public void setAgRef(String agRef) {
		this.agRef = agRef;
	}

	public String getPgRef() {
		return this.pgRef;
	}

	public void setPgRef(String pgRef) {
		this.pgRef = pgRef;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getResCode() {
		return this.resCode;
	}

	public void setResCode(String resCode) {
		this.resCode = resCode;
	}

	public String getResMessage() {
		return this.resMessage;
	}

	public void setResMessage(String resMessage) {
		this.resMessage = resMessage;
	}

	public Integer getFinalStatus() {
		return this.finalStatus;
	}

	public void setFinalStatus(Integer finalStatus) {
		this.finalStatus = finalStatus;
	}

	public String getTxnResponse() {
		return this.txnResponse;
	}

	public void setTxnResponse(String txnResponse) {
		this.txnResponse = txnResponse;
	}

	public String getPgDetails() {
		return this.pgDetails;
	}

	public void setPgDetails(String pgDetails) {
		this.pgDetails = pgDetails;
	}

	public String getFraudDetails() {
		return this.fraudDetails;
	}

	public void setFraudDetails(String fraudDetails) {
		this.fraudDetails = fraudDetails;
	}

	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	public String getCardDetails() {
		return this.cardDetails;
	}

	public void setCardDetails(String cardDetails) {
		this.cardDetails = cardDetails;
	}

	public String getCustDetails() {
		return this.custDetails;
	}

	public void setCustDetails(String custDetails) {
		this.custDetails = custDetails;
	}

	public String getBillDetails() {
		return this.billDetails;
	}

	public void setBillDetails(String billDetails) {
		this.billDetails = billDetails;
	}

	public String getShipDetails() {
		return this.shipDetails;
	}

	public void setShipDetails(String shipDetails) {
		this.shipDetails = shipDetails;
	}

	public String getItemDetails() {
		return this.itemDetails;
	}

	public void setItemDetails(String itemDetails) {
		this.itemDetails = itemDetails;
	}

	public String getOtherDetail() {
		return this.otherDetail;
	}

	public void setOtherDetail(String otherDetail) {
		this.otherDetail = otherDetail;
	}

	public int getUsrId() {
		return this.usrId;
	}

	public void setUsrId(int usrId) {
		this.usrId = usrId;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getUdf_1Data() {
		return udf_1Data;
	}

	public void setUdf_1Data(String udf_1Data) {
		this.udf_1Data = udf_1Data;
	}

	public String getUdf_2Data() {
		return udf_2Data;
	}

	public void setUdf_2Data(String udf_2Data) {
		this.udf_2Data = udf_2Data;
	}

	public String getUdf_3Data() {
		return udf_3Data;
	}

	public void setUdf_3Data(String udf_3Data) {
		this.udf_3Data = udf_3Data;
	}

	public String getUdf_4Data() {
		return udf_4Data;
	}

	public void setUdf_4Data(String udf_4Data) {
		this.udf_4Data = udf_4Data;
	}

	public String getUdf_5Data() {
		return udf_5Data;
	}

	public void setUdf_5Data(String udf_5Data) {
		this.udf_5Data = udf_5Data;
	}
	

}
