package com.mobi.easypayvo;

import java.io.Serializable;
import java.util.Date;

import com.siservices.signup.persistense.UserMasterTblVo;

/**
 * MvpPassportTblId generated by hbm2java
 */
public class PassportTblVo implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer passId;
	private String profileName;
	private String mobileNumber;
	private String dthConsumerNumber;
	private String datacardConsumerNumber;
	private String gasConsumerNumber;
	private String electricityConsumerNumber;
	private String landlineNo;
	private String broadbandNumber;
	private String bankAccountNumber;
	private String reEnterAccountNumber;
	private String bankAccountName;
	private String accountType;
	private String bankName;
	private String ifscName;
	private String upiIdVirtualPaymentAddress;
	private UserMasterTblVo usrId;
	private Integer entryBy;
	private Integer status;
	private Date entryDateTime;
	private Date modifyDateTime;

	public PassportTblVo() {
	}	

	public Integer getPassId() {
		return passId;
	}

	public void setPassId(Integer passId) {
		this.passId = passId;
	}

	public String getProfileName() {
		return this.profileName;
	}

	public void setProfileName(String profileName) {
		this.profileName = profileName;
	}

	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public String getDthConsumerNumber() {
		return this.dthConsumerNumber;
	}

	public void setDthConsumerNumber(String dthConsumerNumber) {
		this.dthConsumerNumber = dthConsumerNumber;
	}

	public String getDatacardConsumerNumber() {
		return this.datacardConsumerNumber;
	}

	public void setDatacardConsumerNumber(String datacardConsumerNumber) {
		this.datacardConsumerNumber = datacardConsumerNumber;
	}

	public String getGasConsumerNumber() {
		return this.gasConsumerNumber;
	}

	public void setGasConsumerNumber(String gasConsumerNumber) {
		this.gasConsumerNumber = gasConsumerNumber;
	}

	public String getElectricityConsumerNumber() {
		return this.electricityConsumerNumber;
	}

	public void setElectricityConsumerNumber(String electricityConsumerNumber) {
		this.electricityConsumerNumber = electricityConsumerNumber;
	}	

	public String getBroadbandNumber() {
		return this.broadbandNumber;
	}

	public void setBroadbandNumber(String broadbandNumber) {
		this.broadbandNumber = broadbandNumber;
	}

	public String getReEnterAccountNumber() {
		return this.reEnterAccountNumber;
	}

	public void setReEnterAccountNumber(String reEnterAccountNumber) {
		this.reEnterAccountNumber = reEnterAccountNumber;
	}

	public String getBankAccountName() {
		return this.bankAccountName;
	}

	public void setBankAccountName(String bankAccountName) {
		this.bankAccountName = bankAccountName;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getIfscName() {
		return this.ifscName;
	}

	public void setIfscName(String ifscName) {
		this.ifscName = ifscName;
	}

	public String getUpiIdVirtualPaymentAddress() {
		return this.upiIdVirtualPaymentAddress;
	}

	public void setUpiIdVirtualPaymentAddress(String upiIdVirtualPaymentAddress) {
		this.upiIdVirtualPaymentAddress = upiIdVirtualPaymentAddress;
	}

	public UserMasterTblVo getUsrId() {
		return usrId;
	}

	public void setUsrId(UserMasterTblVo usrId) {
		this.usrId = usrId;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getEntryDateTime() {
		return this.entryDateTime;
	}

	public void setEntryDateTime(Date entryDateTime) {
		this.entryDateTime = entryDateTime;
	}

	public Date getModifyDateTime() {
		return this.modifyDateTime;
	}

	public void setModifyDateTime(Date modifyDateTime) {
		this.modifyDateTime = modifyDateTime;
	}

	public String getLandlineNo() {
		return landlineNo;
	}

	public void setLandlineNo(String landlineNo) {
		this.landlineNo = landlineNo;
	}

	public String getBankAccountNumber() {
		return bankAccountNumber;
	}

	public void setBankAccountNumber(String bankAccountNumber) {
		this.bankAccountNumber = bankAccountNumber;
	}

}
