package com.pack.timelinefeedvo;

import java.util.Date;

/**
 * MvpComplaintsTbl generated by hbm2java
 */
public class FeedattchTblVO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer ivrBnATTCH_ID;
	private FeedsTblVO ivrBnFEED_ID;
	private String ivrBnATTACH_NAME;
	private String ivrBnTHUMP_IMAGE;
	private Integer ivrBnSTATUS;	
	private Date ivrBnENTRY_DATETIME;
	private Integer ivrBnFILE_TYPE;
	private Date ivrBnMODIFY_DATETIME;
	
	public Integer getIvrBnATTCH_ID() {
		return ivrBnATTCH_ID;
	}
	public void setIvrBnATTCH_ID(Integer ivrBnATTCH_ID) {
		this.ivrBnATTCH_ID = ivrBnATTCH_ID;
	}
	
	
	public FeedsTblVO getIvrBnFEED_ID() {
		return ivrBnFEED_ID;
	}
	public void setIvrBnFEED_ID(FeedsTblVO ivrBnFEED_ID) {
		this.ivrBnFEED_ID = ivrBnFEED_ID;
	}
	public String getIvrBnATTACH_NAME() {
		return ivrBnATTACH_NAME;
	}
	public void setIvrBnATTACH_NAME(String ivrBnATTACH_NAME) {
		this.ivrBnATTACH_NAME = ivrBnATTACH_NAME;
	}
	
	public String getIvrBnTHUMP_IMAGE() {
		return ivrBnTHUMP_IMAGE;
	}
	public void setIvrBnTHUMP_IMAGE(String ivrBnTHUMP_IMAGE) {
		this.ivrBnTHUMP_IMAGE = ivrBnTHUMP_IMAGE;
	}
	public Integer getIvrBnSTATUS() {
		return ivrBnSTATUS;
	}
	public void setIvrBnSTATUS(Integer ivrBnSTATUS) {
		this.ivrBnSTATUS = ivrBnSTATUS;
	}
	public Date getIvrBnENTRY_DATETIME() {
		return ivrBnENTRY_DATETIME;
	}
	public void setIvrBnENTRY_DATETIME(Date ivrBnENTRY_DATETIME) {
		this.ivrBnENTRY_DATETIME = ivrBnENTRY_DATETIME;
	}
	public Integer getIvrBnFILE_TYPE() {
		return ivrBnFILE_TYPE;
	}
	public void setIvrBnFILE_TYPE(Integer ivrBnFILE_TYPE) {
		this.ivrBnFILE_TYPE = ivrBnFILE_TYPE;
	}
	public Date getIvrBnMODIFY_DATETIME() {
		return ivrBnMODIFY_DATETIME;
	}
	public void setIvrBnMODIFY_DATETIME(Date ivrBnMODIFY_DATETIME) {
		this.ivrBnMODIFY_DATETIME = ivrBnMODIFY_DATETIME;
	}	

}
