package com.pack.commonvo;

// default package
// Generated Sep 30, 2016 11:47:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * MvpBloodGroupTbl generated by hbm2java
 */
public class MvpBloodGroupTbl implements java.io.Serializable {

	private Integer bloodGroupId;
	private String bloodGroupName;
	private Integer status;
	private int entryBy;
	private Date entryDatetime;
	private Date modyDatetime;

	public MvpBloodGroupTbl() {
	}

	public MvpBloodGroupTbl(int entryBy, Date modyDatetime) {
		this.entryBy = entryBy;
		this.modyDatetime = modyDatetime;
	}

	public MvpBloodGroupTbl(String bloodGroupName, Integer status, int entryBy,
			Date entryDatetime, Date modyDatetime, Set mvpFamilymbrTbls) {
		this.bloodGroupName = bloodGroupName;
		this.status = status;
		this.entryBy = entryBy;
		this.entryDatetime = entryDatetime;
		this.modyDatetime = modyDatetime;
	}

	public Integer getBloodGroupId() {
		return this.bloodGroupId;
	}

	public void setBloodGroupId(Integer bloodGroupId) {
		this.bloodGroupId = bloodGroupId;
	}

	public String getBloodGroupName() {
		return this.bloodGroupName;
	}

	public void setBloodGroupName(String bloodGroupName) {
		this.bloodGroupName = bloodGroupName;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public int getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(int entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModyDatetime() {
		return this.modyDatetime;
	}

	public void setModyDatetime(Date modyDatetime) {
		this.modyDatetime = modyDatetime;
	}


}
