package com.pack.complaintVO;

import java.util.Date;

/**
 * MvpComplaintsTbl generated by hbm2java
 */
public class ComplaintattchTblVO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer ivrBnATTCH_ID;
	private Integer ivrBnCOMPLAINTS_ID;
	private String ivrBnATTACH_NAME;
	private Integer ivrBnSTATUS;	
	private String thumbImage;
	private Date ivrBnENTRY_DATETIME;
	private Integer ivrBnFILE_TYPE;
	
	public Integer getIvrBnATTCH_ID() {
		return ivrBnATTCH_ID;
	}
	public void setIvrBnATTCH_ID(Integer ivrBnATTCH_ID) {
		this.ivrBnATTCH_ID = ivrBnATTCH_ID;
	}
	public Integer getIvrBnCOMPLAINTS_ID() {
		return ivrBnCOMPLAINTS_ID;
	}
	public void setIvrBnCOMPLAINTS_ID(Integer ivrBnCOMPLAINTS_ID) {
		this.ivrBnCOMPLAINTS_ID = ivrBnCOMPLAINTS_ID;
	}
	public String getIvrBnATTACH_NAME() {
		return ivrBnATTACH_NAME;
	}
	public void setIvrBnATTACH_NAME(String ivrBnATTACH_NAME) {
		this.ivrBnATTACH_NAME = ivrBnATTACH_NAME;
	}
	public Integer getIvrBnSTATUS() {
		return ivrBnSTATUS;
	}
	public void setIvrBnSTATUS(Integer ivrBnSTATUS) {
		this.ivrBnSTATUS = ivrBnSTATUS;
	}
	public Date getIvrBnENTRY_DATETIME() {
		return ivrBnENTRY_DATETIME;
	}
	public void setIvrBnENTRY_DATETIME(Date ivrBnENTRY_DATETIME) {
		this.ivrBnENTRY_DATETIME = ivrBnENTRY_DATETIME;
	}
	public Integer getIvrBnFILE_TYPE() {
		return ivrBnFILE_TYPE;
	}
	public void setIvrBnFILE_TYPE(Integer ivrBnFILE_TYPE) {
		this.ivrBnFILE_TYPE = ivrBnFILE_TYPE;
	}
	public String getThumbImage() {
		return thumbImage;
	}
	public void setThumbImage(String thumbImage) {
		this.thumbImage = thumbImage;
	}
	
	
	
	
	

}
