package com.siservices.socialmedia.persistense;

// default package
// Generated Jun 13, 2016 10:10:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.siservices.signup.persistense.UserMasterTblVo;

/**
 * MvpSocialProTbl generated by hbm2java
 */
public class MvpSocialProTbl implements java.io.Serializable {

	private Integer uniqueId;
	private UserMasterTblVo userId;
	private String name;
	private String firstName;
	private String lastName;
	private String socialId;
	private String emailId;
	private String gender;
	private String pictureUrl;
	private String pictureUrlMobile;
	private String location;
	private String address;
	private String socialNw;
	private Integer loginCount;
	private String longaccesstoken;
	private String tokenExpire;
	private Integer actSts;
	private Date enrtyDatetime;
	private Date modifyDatetime;

	public MvpSocialProTbl() {
	}

	public MvpSocialProTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public MvpSocialProTbl(UserMasterTblVo userId, String name, String firstName,
			String lastName, String socialId, String emailId, String gender,
			String pictureUrl, String pictureUrlMobile, String location,
			String address, String socialNw, Integer loginCount,
			String longaccesstoken, String tokenExpire, Integer actSts,
			Date enrtyDatetime, Date modifyDatetime) {
		this.userId = userId;
		this.name = name;
		this.firstName = firstName;
		this.lastName = lastName;
		this.socialId = socialId;
		this.emailId = emailId;
		this.gender = gender;
		this.pictureUrl = pictureUrl;
		this.pictureUrlMobile = pictureUrlMobile;
		this.location = location;
		this.address = address;
		this.socialNw = socialNw;
		this.loginCount = loginCount;
		this.longaccesstoken = longaccesstoken;
		this.tokenExpire = tokenExpire;
		this.actSts = actSts;
		this.enrtyDatetime = enrtyDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(Integer uniqueId) {
		this.uniqueId = uniqueId;
	}

	

	public UserMasterTblVo getUserId() {
		return userId;
	}

	public void setUserId(UserMasterTblVo userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getSocialId() {
		return this.socialId;
	}

	public void setSocialId(String socialId) {
		this.socialId = socialId;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getPictureUrl() {
		return this.pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}

	public String getPictureUrlMobile() {
		return this.pictureUrlMobile;
	}

	public void setPictureUrlMobile(String pictureUrlMobile) {
		this.pictureUrlMobile = pictureUrlMobile;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSocialNw() {
		return this.socialNw;
	}

	public void setSocialNw(String socialNw) {
		this.socialNw = socialNw;
	}

	public Integer getLoginCount() {
		return this.loginCount;
	}

	public void setLoginCount(Integer loginCount) {
		this.loginCount = loginCount;
	}

	public String getLongaccesstoken() {
		return this.longaccesstoken;
	}

	public void setLongaccesstoken(String longaccesstoken) {
		this.longaccesstoken = longaccesstoken;
	}

	public String getTokenExpire() {
		return this.tokenExpire;
	}

	public void setTokenExpire(String tokenExpire) {
		this.tokenExpire = tokenExpire;
	}

	public Integer getActSts() {
		return this.actSts;
	}

	public void setActSts(Integer actSts) {
		this.actSts = actSts;
	}

	public Date getEnrtyDatetime() {
		return this.enrtyDatetime;
	}

	public void setEnrtyDatetime(Date enrtyDatetime) {
		this.enrtyDatetime = enrtyDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

}
