package com.siservices.forumVo;

// default package
// Generated Jul 21, 2016 6:06:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

import com.siservices.signup.persistense.UserMasterTblVo;
import com.siservices.uam.persistense.GroupMasterTblVo;



/**
 * MvpFourmTopicsTbl generated by hbm2java
 */
public class MvpFourmTopicsTbl implements java.io.Serializable {

	private Integer topicsId;
	private GroupMasterTblVo groupCode;
	private UserMasterTblVo userId;
	private String topicsName;
	private String topicsDesc;
	private String keyForSearch;
	private Date validOnDate;
	private Integer status;
	private Integer entryBy;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpFourmTopicsTbl() {
	}

	public MvpFourmTopicsTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public MvpFourmTopicsTbl(UserMasterTblVo usrRegTbl, GroupMasterTblVo groupMstTbl,
			String topicsName, String topicsDesc, String keyForSearch,
			Date validOnDate, Integer status, Integer entryBy,
			Date entryDatetime, Date modifyDatetime, Set mvpFourmDiscussTbls) {
		this.userId = usrRegTbl;
		this.groupCode = groupMstTbl;
		this.topicsName = topicsName;
		this.topicsDesc = topicsDesc;
		this.keyForSearch = keyForSearch;
		this.validOnDate = validOnDate;
		this.status = status;
		this.entryBy = entryBy;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getTopicsId() {
		return this.topicsId;
	}

	public void setTopicsId(Integer topicsId) {
		this.topicsId = topicsId;
	}

	
	public String getTopicsName() {
		return this.topicsName;
	}

	public void setTopicsName(String topicsName) {
		this.topicsName = topicsName;
	}

	public String getTopicsDesc() {
		return this.topicsDesc;
	}

	public void setTopicsDesc(String topicsDesc) {
		this.topicsDesc = topicsDesc;
	}

	public String getKeyForSearch() {
		return this.keyForSearch;
	}

	public void setKeyForSearch(String keyForSearch) {
		this.keyForSearch = keyForSearch;
	}

	public Date getValidOnDate() {
		return this.validOnDate;
	}

	public void setValidOnDate(Date validOnDate) {
		this.validOnDate = validOnDate;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public GroupMasterTblVo getGroupCode() {
		return groupCode;
	}

	public void setGroupCode(GroupMasterTblVo groupCode) {
		this.groupCode = groupCode;
	}

	public UserMasterTblVo getUserId() {
		return userId;
	}

	public void setUserId(UserMasterTblVo userId) {
		this.userId = userId;
	}

}
