package com.socialindiaservices.vo;

import java.util.Date;

import com.pack.commonvo.IDCardMasterTblVO;
import com.pack.commonvo.SkillMasterTblVO;
import com.siservices.signup.persistense.UserMasterTblVo;

/**
 * MvpGatepassDetailTbl generated by hbm2java
 */
public class MvpGatepassDetailTbl implements java.io.Serializable {

	private Integer passId;
	private SkillMasterTblVO mvpSkillTbl;
	private UserMasterTblVo entryBy;
	private IDCardMasterTblVO mvpIdcardTbl;
	private String gatepassNo;
	private String visitorName;
	private String visitorImage;
	private Integer passType;
	private Date dateOfBirth;
	private String email;
	private String mobileNo;
	private String idCardNumber;
	private Date issueDate;
	private Date issueTime;
	private Date expiryDate;
	private String description;
	private Integer noOfAccompanies;
	private String vehicleNumber;
	private Integer statusFlag;
	private Date entryDatetime;
	private Date modifyDatetime;
	private Integer modifyBy;
	private String visitorLocation;
	private Integer visitorstatus;

	public MvpGatepassDetailTbl() {
	}

	public MvpGatepassDetailTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	/*public MvpGatepassDetailTbl(SkillMasterTblVO mvpSkillTbl, UserMasterTblVo usrRegTbl,
			IDCardMasterTblVO mvpIdcardTbl, String gatepassNo, String visitorName,
			String visitorImage, Integer passType, Date dateOfBirth,
			String email, String mobileNo, String idCardNumber,
			Date issueDateTime, Date expiryDate, String description,
			Integer noOfAccompanies, String vehicleNumber, Integer statusFlag,
			Date entryDatetime, Date modifyDatetime, Integer modifyBy) {
		this.mvpSkillTbl = mvpSkillTbl;
		this.usrRegTbl = usrRegTbl;
		this.mvpIdcardTbl = mvpIdcardTbl;
		this.gatepassNo = gatepassNo;
		this.visitorName = visitorName;
		this.visitorImage = visitorImage;
		this.passType = passType;
		this.dateOfBirth = dateOfBirth;
		this.email = email;
		this.mobileNo = mobileNo;
		this.idCardNumber = idCardNumber;
		this.issueDateTime = issueDateTime;
		this.expiryDate = expiryDate;
		this.description = description;
		this.noOfAccompanies = noOfAccompanies;
		this.vehicleNumber = vehicleNumber;
		this.statusFlag = statusFlag;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
		this.modifyBy = modifyBy;
	}*/

	public Integer getPassId() {
		return this.passId;
	}

	public Integer getVisitorstatus() {
		return visitorstatus;
	}

	public void setVisitorstatus(Integer visitorstatus) {
		this.visitorstatus = visitorstatus;
	}

	public void setPassId(Integer passId) {
		this.passId = passId;
	}



	public SkillMasterTblVO getMvpSkillTbl() {
		return mvpSkillTbl;
	}

	public void setMvpSkillTbl(SkillMasterTblVO mvpSkillTbl) {
		this.mvpSkillTbl = mvpSkillTbl;
	}



	public UserMasterTblVo getEntryBy() {
		return entryBy;
	}

	public void setEntryBy(UserMasterTblVo entryBy) {
		this.entryBy = entryBy;
	}

	public IDCardMasterTblVO getMvpIdcardTbl() {
		return mvpIdcardTbl;
	}

	public void setMvpIdcardTbl(IDCardMasterTblVO mvpIdcardTbl) {
		this.mvpIdcardTbl = mvpIdcardTbl;
	}

	public String getGatepassNo() {
		return this.gatepassNo;
	}

	public void setGatepassNo(String gatepassNo) {
		this.gatepassNo = gatepassNo;
	}

	public String getVisitorName() {
		return this.visitorName;
	}

	public void setVisitorName(String visitorName) {
		this.visitorName = visitorName;
	}

	public String getVisitorImage() {
		return this.visitorImage;
	}

	public void setVisitorImage(String visitorImage) {
		this.visitorImage = visitorImage;
	}

	public Integer getPassType() {
		return this.passType;
	}

	public void setPassType(Integer passType) {
		this.passType = passType;
	}



	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getIdCardNumber() {
		return this.idCardNumber;
	}

	public void setIdCardNumber(String idCardNumber) {
		this.idCardNumber = idCardNumber;
	}





	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Date getIssueDate() {
		return issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}



	public Date getIssueTime() {
		return issueTime;
	}

	public void setIssueTime(Date issueTime) {
		this.issueTime = issueTime;
	}

	public Date getExpiryDate() {
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getNoOfAccompanies() {
		return this.noOfAccompanies;
	}

	public void setNoOfAccompanies(Integer noOfAccompanies) {
		this.noOfAccompanies = noOfAccompanies;
	}

	public String getVehicleNumber() {
		return this.vehicleNumber;
	}

	public void setVehicleNumber(String vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	public Integer getStatusFlag() {
		return this.statusFlag;
	}

	public void setStatusFlag(Integer statusFlag) {
		this.statusFlag = statusFlag;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	public String getVisitorLocation() {
		return visitorLocation;
	}

	public void setVisitorLocation(String visitorLocation) {
		this.visitorLocation = visitorLocation;
	}


}
