package com.siservices.societyMgmt;

// default package
// Generated Jul 21, 2016 6:06:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.siservices.signup.persistense.UserMasterTblVo;
import com.siservices.uam.persistense.SocietyMstTbl;

/**
 * MvpSocietyAccTbl generated by hbm2java
 */
public class MvpSocietyAccTbl implements java.io.Serializable {

	private Integer societyAccId;
	private SocietyMstTbl societyId;
	private UserMasterTblVo userId;
	private String bankName;
	private String ifscCode;
	private String bankAccName;
	private String bankAccNo;
	private Integer statusFlag;
	private Integer entryBy;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpSocietyAccTbl() {
	}

	public MvpSocietyAccTbl(String bankName, String bankAccName, String bankAccNo,
			Date modifyDatetime) {
		this.bankName = bankName;
		this.bankAccName = bankAccName;
		this.bankAccNo = bankAccNo;
		this.modifyDatetime = modifyDatetime;
	}

	public MvpSocietyAccTbl(SocietyMstTbl societyMstTbl, UserMasterTblVo usrRegTbl,
			String bankName, String ifscCode, String bankAccName,
			String bankAccNo, Integer statusFlag, Integer entryBy,
			Date entryDatetime, Date modifyDatetime) {
		this.societyId = societyMstTbl;
		this.userId = usrRegTbl;
		this.bankName = bankName;
		this.ifscCode = ifscCode;
		this.bankAccName = bankAccName;
		this.bankAccNo = bankAccNo;
		this.statusFlag = statusFlag;
		this.entryBy = entryBy;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getSocietyAccId() {
		return this.societyAccId;
	}

	public void setSocietyAccId(Integer societyAccId) {
		this.societyAccId = societyAccId;
	}

	public SocietyMstTbl getSocietyId() {
		return societyId;
	}

	public void setSocietyId(SocietyMstTbl societyId) {
		this.societyId = societyId;
	}

	public UserMasterTblVo getUserId() {
		return userId;
	}

	public void setUserId(UserMasterTblVo userId) {
		this.userId = userId;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getIfscCode() {
		return this.ifscCode;
	}

	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}

	public String getBankAccName() {
		return this.bankAccName;
	}

	public void setBankAccName(String bankAccName) {
		this.bankAccName = bankAccName;
	}

	

	public String getBankAccNo() {
		return bankAccNo;
	}

	public void setBankAccNo(String bankAccNo) {
		this.bankAccNo = bankAccNo;
	}

	public Integer getStatusFlag() {
		return this.statusFlag;
	}

	public void setStatusFlag(Integer statusFlag) {
		this.statusFlag = statusFlag;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

}
