package com.siservices.societyMgmt;

// default package
// Generated Jul 20, 2016 4:29:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.siservices.uam.persistense.SocietyMstTbl;

/**
 * SocietyWingsDetailTbl generated by hbm2java
 */
public class SocietyWingsDetailTbl implements java.io.Serializable {

	private Integer wingsId;
	private SocietyMstTbl societyId;
	private String wingsName;
	private Integer status;
	private Integer enrtyBy;
	private Date entryDate;
	private Date modifyDate;

	public SocietyWingsDetailTbl() {
	}

	public SocietyWingsDetailTbl(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public SocietyWingsDetailTbl(SocietyMstTbl societyMstTbl, String wingsName,
			Integer status, Integer enrtyBy, Date entryDate, Date modifyDate) {
		this.societyId = societyMstTbl;
		this.wingsName = wingsName;
		this.status = status;
		this.enrtyBy = enrtyBy;
		this.entryDate = entryDate;
		this.modifyDate = modifyDate;
	}

	public Integer getWingsId() {
		return this.wingsId;
	}

	public void setWingsId(Integer wingsId) {
		this.wingsId = wingsId;
	}


	public SocietyMstTbl getSocietyId() {
		return societyId;
	}

	public void setSocietyId(SocietyMstTbl societyId) {
		this.societyId = societyId;
	}

	public String getWingsName() {
		return this.wingsName;
	}

	public void setWingsName(String wingsName) {
		this.wingsName = wingsName;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEnrtyBy() {
		return this.enrtyBy;
	}

	public void setEnrtyBy(Integer enrtyBy) {
		this.enrtyBy = enrtyBy;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
