package com.siservices.uam.persistense;

// default package
// Generated Jul 20, 2016 4:29:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.pack.commonvo.KnownusTblVO;
import com.pack.commonvo.MvpBloodGroupTbl;
import com.pack.commonvo.MvpTitleMstTbl;
import com.siservices.signup.persistense.UserMasterTblVo;

/**
 * MvpFamilymbrTbl generated by hbm2java
 */
public class MvpFamilymbrTbl implements java.io.Serializable {

	private Integer fmbrTntId;
	private UserMasterTblVo userId;
	private KnownusTblVO iVOKNOWN_US_ID;
	private MvpBloodGroupTbl bloodGroupId;
	private MvpTitleMstTbl titleId;
	private String fmbrName;
	private String fmbrGender;
	private Integer fmbrAge;
	private Date fmbrDob;
	private String fmbrEmail;
	private String fmbrPswd;
	private String fmbrPhNo;
	private String fmbrIsdCode;
	private String fmbrAdd;
	private Integer fmbrCntry;
	private Integer fmbrState;
	private Integer fmbrCity;
	private Integer fmbrIdCardTyp;
	private String fmbrIdCardNo;
	private Integer fmbrType;
	private Integer fmbrProfAcc;
	private Integer status;
	private Integer entryByGrpId;
	private Integer entryBy;
	private Date entryDatetime;
	private Date modifyDatetime;
	
	private Integer mobileOtpFlg;
	private Integer EmailVerifyFlg;
	
	private Integer socialType;
	  private String socialId;
	  private String socialProfileUrl;
	
	private Integer isInvited;

	public MvpFamilymbrTbl() {
	}

	public MvpFamilymbrTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public MvpFamilymbrTbl(UserMasterTblVo userId, String fmbrName,
			String fmbrGender, Integer fmbrAge, Date fmbrDob, String fmbrEmail,
			String fmbrPswd, String fmbrPhNo, String fmbrIsdCode,
			String fmbrAdd, Integer fmbrCntry, Integer fmbrState,
			Integer fmbrCity, Integer fmbrIdCardTyp, String fmbrIdCardNo,
			Integer fmbrType, Integer fmbrProfAcc, Integer status,
			Integer entryByGrpId, Integer entryBy, Date entryDatetime,
			Date modifyDatetime) {
		this.userId = userId;
		this.fmbrName = fmbrName;
		this.fmbrGender = fmbrGender;
		this.fmbrAge = fmbrAge;
		this.fmbrDob = fmbrDob;
		this.fmbrEmail = fmbrEmail;
		this.fmbrPswd = fmbrPswd;
		this.fmbrPhNo = fmbrPhNo;
		this.fmbrIsdCode = fmbrIsdCode;
		this.fmbrAdd = fmbrAdd;
		this.fmbrCntry = fmbrCntry;
		this.fmbrState = fmbrState;
		this.fmbrCity = fmbrCity;
		this.fmbrIdCardTyp = fmbrIdCardTyp;
		this.fmbrIdCardNo = fmbrIdCardNo;
		this.fmbrType = fmbrType;
		this.fmbrProfAcc = fmbrProfAcc;
		this.status = status;
		this.entryByGrpId = entryByGrpId;
		this.entryBy = entryBy;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getFmbrTntId() {
		return this.fmbrTntId;
	}

	public void setFmbrTntId(Integer fmbrTntId) {
		this.fmbrTntId = fmbrTntId;
	}

	public UserMasterTblVo getUserId() {
		return userId;
	}

	public void setUserId(UserMasterTblVo userId) {
		this.userId = userId;
	}

	public String getFmbrName() {
		return this.fmbrName;
	}

	public void setFmbrName(String fmbrName) {
		this.fmbrName = fmbrName;
	}

	public String getFmbrGender() {
		return this.fmbrGender;
	}

	public void setFmbrGender(String fmbrGender) {
		this.fmbrGender = fmbrGender;
	}

	public Integer getFmbrAge() {
		return this.fmbrAge;
	}

	public void setFmbrAge(Integer fmbrAge) {
		this.fmbrAge = fmbrAge;
	}

	public Date getFmbrDob() {
		return this.fmbrDob;
	}

	public void setFmbrDob(Date fmbrDob) {
		this.fmbrDob = fmbrDob;
	}

	public String getFmbrEmail() {
		return this.fmbrEmail;
	}

	public void setFmbrEmail(String fmbrEmail) {
		this.fmbrEmail = fmbrEmail;
	}

	public String getFmbrPswd() {
		return this.fmbrPswd;
	}

	public void setFmbrPswd(String fmbrPswd) {
		this.fmbrPswd = fmbrPswd;
	}

	public String getFmbrPhNo() {
		return this.fmbrPhNo;
	}

	public void setFmbrPhNo(String fmbrPhNo) {
		this.fmbrPhNo = fmbrPhNo;
	}

	public String getFmbrIsdCode() {
		return this.fmbrIsdCode;
	}

	public void setFmbrIsdCode(String fmbrIsdCode) {
		this.fmbrIsdCode = fmbrIsdCode;
	}

	public String getFmbrAdd() {
		return this.fmbrAdd;
	}

	public void setFmbrAdd(String fmbrAdd) {
		this.fmbrAdd = fmbrAdd;
	}

	public Integer getFmbrCntry() {
		return this.fmbrCntry;
	}

	public void setFmbrCntry(Integer fmbrCntry) {
		this.fmbrCntry = fmbrCntry;
	}

	public Integer getFmbrState() {
		return this.fmbrState;
	}

	public void setFmbrState(Integer fmbrState) {
		this.fmbrState = fmbrState;
	}

	public Integer getFmbrCity() {
		return this.fmbrCity;
	}

	public void setFmbrCity(Integer fmbrCity) {
		this.fmbrCity = fmbrCity;
	}

	public Integer getFmbrIdCardTyp() {
		return this.fmbrIdCardTyp;
	}

	public void setFmbrIdCardTyp(Integer fmbrIdCardTyp) {
		this.fmbrIdCardTyp = fmbrIdCardTyp;
	}

	public String getFmbrIdCardNo() {
		return this.fmbrIdCardNo;
	}

	public void setFmbrIdCardNo(String fmbrIdCardNo) {
		this.fmbrIdCardNo = fmbrIdCardNo;
	}

	public Integer getFmbrType() {
		return this.fmbrType;
	}

	public void setFmbrType(Integer fmbrType) {
		this.fmbrType = fmbrType;
	}

	public Integer getFmbrProfAcc() {
		return this.fmbrProfAcc;
	}

	public void setFmbrProfAcc(Integer fmbrProfAcc) {
		this.fmbrProfAcc = fmbrProfAcc;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEntryByGrpId() {
		return this.entryByGrpId;
	}

	public void setEntryByGrpId(Integer entryByGrpId) {
		this.entryByGrpId = entryByGrpId;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getIsInvited() {
		return isInvited;
	}

	public void setIsInvited(Integer isInvited) {
		this.isInvited = isInvited;
	}

	public KnownusTblVO getiVOKNOWN_US_ID() {
		return iVOKNOWN_US_ID;
	}

	public void setiVOKNOWN_US_ID(KnownusTblVO iVOKNOWN_US_ID) {
		this.iVOKNOWN_US_ID = iVOKNOWN_US_ID;
	}

	public MvpBloodGroupTbl getBloodGroupId() {
		return bloodGroupId;
	}

	public void setBloodGroupId(MvpBloodGroupTbl bloodGroupId) {
		this.bloodGroupId = bloodGroupId;
	}

	public MvpTitleMstTbl getTitleId() {
		return titleId;
	}

	public void setTitleId(MvpTitleMstTbl titleId) {
		this.titleId = titleId;
	}

	public Integer getMobileOtpFlg() {
		return mobileOtpFlg;
	}

	public void setMobileOtpFlg(Integer mobileOtpFlg) {
		this.mobileOtpFlg = mobileOtpFlg;
	}

	public Integer getEmailVerifyFlg() {
		return EmailVerifyFlg;
	}

	public void setEmailVerifyFlg(Integer emailVerifyFlg) {
		EmailVerifyFlg = emailVerifyFlg;
	}

	public Integer getSocialType() {
		return socialType;
	}

	public void setSocialType(Integer socialType) {
		this.socialType = socialType;
	}

	public String getSocialId() {
		return socialId;
	}

	public void setSocialId(String socialId) {
		this.socialId = socialId;
	}

	public String getSocialProfileUrl() {
		return socialProfileUrl;
	}

	public void setSocialProfileUrl(String socialProfileUrl) {
		this.socialProfileUrl = socialProfileUrl;
	}

}
