package com.siservices.uam.persistense;

// default package
// Generated Jun 14, 2016 2:48:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SocietyMstTbl generated by hbm2java
 */
public class SocietyMstTbl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer societyId;
	private TownshipMstTbl townshipId;
	private String societyUniqyeId;
	private String societyName;
	private String activationKey;
	private int noOfMemebers;
	
	private String oldActivationKey;
	private String noOfBlocksWings;
	private String registerNo;
	private String colourCode;
	private String imprintName;
	private String logoImage;
	private String icoImage;
	private int statusFlag;
	private Integer entryby;
	private Date entryDatetime;
	private Date modifyDatetime;
	
	private String gstin;
	private String hsn;

	public SocietyMstTbl() {
	}

	public SocietyMstTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public SocietyMstTbl(TownshipMstTbl townshipId, String societyUniqyeId,
			String societyName, Integer entryby, Date entryDatetime,
			Date modifyDatetime) {
		this.townshipId = townshipId;
		this.societyUniqyeId = societyUniqyeId;
		this.societyName = societyName;
		this.entryby = entryby;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getSocietyId() {
		return this.societyId;
	}

	public void setSocietyId(Integer societyId) {
		this.societyId = societyId;
	}

	

	public TownshipMstTbl getTownshipId() {
		return townshipId;
	}

	public void setTownshipId(TownshipMstTbl townshipId) {
		this.townshipId = townshipId;
	}

	public String getSocietyUniqyeId() {
		return this.societyUniqyeId;
	}

	public void setSocietyUniqyeId(String societyUniqyeId) {
		this.societyUniqyeId = societyUniqyeId;
	}

	public String getSocietyName() {
		return this.societyName;
	}

	public void setSocietyName(String societyName) {
		this.societyName = societyName;
	}

	public Integer getEntryby() {
		return this.entryby;
	}

	public void setEntryby(Integer entryby) {
		this.entryby = entryby;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getActivationKey() {
		return activationKey;
	}

	public void setActivationKey(String activationKey) {
		this.activationKey = activationKey;
	}

	public int getNoOfMemebers() {
		return noOfMemebers;
	}

	public void setNoOfMemebers(int noOfMemebers) {
		this.noOfMemebers = noOfMemebers;
	}

	public int getStatusFlag() {
		return statusFlag;
	}

	public void setStatusFlag(int statusFlag) {
		this.statusFlag = statusFlag;
	}

	public String getOldActivationKey() {
		return oldActivationKey;
	}

	public void setOldActivationKey(String oldActivationKey) {
		this.oldActivationKey = oldActivationKey;
	}

	public String getNoOfBlocksWings() {
		return noOfBlocksWings;
	}

	public void setNoOfBlocksWings(String noOfBlocksWings) {
		this.noOfBlocksWings = noOfBlocksWings;
	}

	public String getRegisterNo() {
		return registerNo;
	}

	public void setRegisterNo(String registerNo) {
		this.registerNo = registerNo;
	}

	public String getColourCode() {
		return colourCode;
	}

	public void setColourCode(String colourCode) {
		this.colourCode = colourCode;
	}

	public String getImprintName() {
		return imprintName;
	}

	public void setImprintName(String imprintName) {
		this.imprintName = imprintName;
	}

	public String getLogoImage() {
		return logoImage;
	}

	public void setLogoImage(String logoImage) {
		this.logoImage = logoImage;
	}

	public String getIcoImage() {
		return icoImage;
	}

	public void setIcoImage(String icoImage) {
		this.icoImage = icoImage;
	}

	public String getGstin() {
		return gstin;
	}

	public void setGstin(String gstin) {
		this.gstin = gstin;
	}

	public String getHsn() {
		return hsn;
	}

	public void setHsn(String hsn) {
		this.hsn = hsn;
	}


}
