package com.siservices.materialVo;

// default package
// Generated Aug 16, 2016 3:19:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MaterialCategoryTbl generated by hbm2java
 */
public class MaterialCategoryTbl implements java.io.Serializable {

	private Integer materialCategoryId;
	private String materialName;
	private Integer status;
	private Integer entryBy;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MaterialCategoryTbl() {
	}

	public MaterialCategoryTbl(String materialName, Date modifyDatetime) {
		this.materialName = materialName;
		this.modifyDatetime = modifyDatetime;
	}

	public MaterialCategoryTbl(String materialName, Integer status,
			Integer entryBy, Date entryDatetime, Date modifyDatetime,
			Set mvpMaterialTbls) {
		this.materialName = materialName;
		this.status = status;
		this.entryBy = entryBy;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getMaterialCategoryId() {
		return this.materialCategoryId;
	}

	public void setMaterialCategoryId(Integer materialCategoryId) {
		this.materialCategoryId = materialCategoryId;
	}

	public String getMaterialName() {
		return this.materialName;
	}

	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

}
