package com.siservices.materialVo;

// default package
// Generated Aug 16, 2016 3:19:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.siservices.uam.persistense.SocietyMstTbl;

/**
 * MvpMaterialTbl generated by hbm2java
 */
public class MvpMaterialTbl implements java.io.Serializable {

	private Integer materialId;
	private SocietyMstTbl societyId;
	private MaterialCategoryTbl materialCategoryId;
	private String materialName;
	private String materialDesc;
	private Integer materialQnty;
	private Integer totalQnty;
	private Integer usedQnty;
	private Float materialPrice;
	private Date purchaseDate;
	private Integer status;
	private Integer entryBy;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpMaterialTbl() {
	}

	public MvpMaterialTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public MvpMaterialTbl(SocietyMstTbl societyMstTbl,
			MaterialCategoryTbl materialCategoryTbl, String materialName,
			String materialDesc, Integer materialQnty, Integer totalQnty,
			Integer usedQnty, Float materialPrice, Date purchaseDate,
			Integer status, Integer entryBy, Date entryDatetime,
			Date modifyDatetime) {
		this.societyId = societyMstTbl;
		this.materialCategoryId = materialCategoryTbl;
		this.materialName = materialName;
		this.materialDesc = materialDesc;
		this.materialQnty = materialQnty;
		this.totalQnty = totalQnty;
		this.usedQnty = usedQnty;
		this.materialPrice = materialPrice;
		this.purchaseDate = purchaseDate;
		this.status = status;
		this.entryBy = entryBy;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getMaterialId() {
		return this.materialId;
	}

	public void setMaterialId(Integer materialId) {
		this.materialId = materialId;
	}


	public SocietyMstTbl getSocietyId() {
		return societyId;
	}

	public void setSocietyId(SocietyMstTbl societyId) {
		this.societyId = societyId;
	}

	public MaterialCategoryTbl getMaterialCategoryId() {
		return materialCategoryId;
	}

	public void setMaterialCategoryId(MaterialCategoryTbl materialCategoryId) {
		this.materialCategoryId = materialCategoryId;
	}

	public String getMaterialName() {
		return this.materialName;
	}

	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}

	public String getMaterialDesc() {
		return this.materialDesc;
	}

	public void setMaterialDesc(String materialDesc) {
		this.materialDesc = materialDesc;
	}

	public Integer getMaterialQnty() {
		return this.materialQnty;
	}

	public void setMaterialQnty(Integer materialQnty) {
		this.materialQnty = materialQnty;
	}

	public Integer getTotalQnty() {
		return this.totalQnty;
	}

	public void setTotalQnty(Integer totalQnty) {
		this.totalQnty = totalQnty;
	}

	public Integer getUsedQnty() {
		return this.usedQnty;
	}

	public void setUsedQnty(Integer usedQnty) {
		this.usedQnty = usedQnty;
	}

	public Float getMaterialPrice() {
		return this.materialPrice;
	}

	public void setMaterialPrice(Float materialPrice) {
		this.materialPrice = materialPrice;
	}

	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getEntryBy() {
		return this.entryBy;
	}

	public void setEntryBy(Integer entryBy) {
		this.entryBy = entryBy;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

}
