package com.mobile.wishlist;

// default package
// Generated Sep 29, 2016 12:47:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.pack.commonvo.CategoryMasterTblVO;
import com.siservices.signup.persistense.UserMasterTblVo;

/**
 * MvpWishlistTbl generated by hbm2java
 */
public class MvpWishlistTbl implements java.io.Serializable {

	private Integer wishlistId;
	private UserMasterTblVo userId;
	private CategoryMasterTblVO iVOCATEGORY_ID;
	private String description;
	private Integer buySellFlg;
	private Date fromDate;
	private Date toDate;
	private Integer actFlg;
	private Date enrtyDatetime;
	private Date modifyDatetime;

	public MvpWishlistTbl() {
	}

	public MvpWishlistTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public MvpWishlistTbl(UserMasterTblVo usrRegTbl, CategoryMasterTblVO categoryMstTbl,
			String description, Integer buySellFlg, Date fromDate, Date toDate,
			Integer actFlg, Date enrtyDatetime, Date modifyDatetime) {
		this.userId = usrRegTbl;
		this.iVOCATEGORY_ID = categoryMstTbl;
		this.description = description;
		this.buySellFlg = buySellFlg;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.actFlg = actFlg;
		this.enrtyDatetime = enrtyDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getWishlistId() {
		return this.wishlistId;
	}

	public void setWishlistId(Integer wishlistId) {
		this.wishlistId = wishlistId;
	}


	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getBuySellFlg() {
		return this.buySellFlg;
	}

	public void setBuySellFlg(Integer buySellFlg) {
		this.buySellFlg = buySellFlg;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public Integer getActFlg() {
		return this.actFlg;
	}

	public void setActFlg(Integer actFlg) {
		this.actFlg = actFlg;
	}

	public Date getEnrtyDatetime() {
		return this.enrtyDatetime;
	}

	public void setEnrtyDatetime(Date enrtyDatetime) {
		this.enrtyDatetime = enrtyDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public UserMasterTblVo getUserId() {
		return userId;
	}

	public void setUserId(UserMasterTblVo userId) {
		this.userId = userId;
	}

	public CategoryMasterTblVO getiVOCATEGORY_ID() {
		return iVOCATEGORY_ID;
	}

	public void setiVOCATEGORY_ID(CategoryMasterTblVO iVOCATEGORY_ID) {
		this.iVOCATEGORY_ID = iVOCATEGORY_ID;
	}

}
