package com.mobi.contents;

import java.util.Date;

/**
 * MvpFaqMstTbl generated by hbm2java
 */
public class MvpFaqMstTbl implements java.io.Serializable {

	private Integer faqId;
	private String faqQuestion;
	private String faqAnswer;
	private Integer status;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpFaqMstTbl() {
	}

	public Integer getFaqId() {
		return this.faqId;
	}

	public void setFaqId(Integer faqId) {
		this.faqId = faqId;
	}

	public String getFaqQuestion() {
		return this.faqQuestion;
	}

	public void setFaqQuestion(String faqQuestion) {
		this.faqQuestion = faqQuestion;
	}

	public String getFaqAnswer() {
		return this.faqAnswer;
	}

	public void setFaqAnswer(String faqAnswer) {
		this.faqAnswer = faqAnswer;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

}
