package com.mobi.networkUserListVO;

// default package
// Generated Sep 30, 2016 11:47:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.pack.commonvo.KnownusTblVO;
import com.siservices.signup.persistense.UserMasterTblVo;

/**
 * MvpNetworkTbl generated by hbm2java
 */
public class MvpNetworkTbl implements java.io.Serializable {

	private Integer networkId;
	private UserMasterTblVo usrParentUsrId;
	private UserMasterTblVo usrConnectedUsrId;
	private String descr;
	private KnownusTblVO iVOKNOWN_US_ID;
	private Integer connStsFlg;
	private Date entryDatetime;
	private Date modifyDatetime;

	public MvpNetworkTbl() {
	}

	public MvpNetworkTbl(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public MvpNetworkTbl(UserMasterTblVo usrRegTblByParentUsrId,
			UserMasterTblVo usrRegTblByConnectedUsrId, String descr, String knowsUs,
			Integer connStsFlg, Date entryDatetime, Date modifyDatetime) {
		this.usrParentUsrId = usrRegTblByParentUsrId;
		this.usrConnectedUsrId = usrRegTblByConnectedUsrId;
		this.descr = descr;
		this.connStsFlg = connStsFlg;
		this.entryDatetime = entryDatetime;
		this.modifyDatetime = modifyDatetime;
	}

	public Integer getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(Integer networkId) {
		this.networkId = networkId;
	}

	

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public Integer getConnStsFlg() {
		return this.connStsFlg;
	}

	public void setConnStsFlg(Integer connStsFlg) {
		this.connStsFlg = connStsFlg;
	}

	public Date getEntryDatetime() {
		return this.entryDatetime;
	}

	public void setEntryDatetime(Date entryDatetime) {
		this.entryDatetime = entryDatetime;
	}

	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public UserMasterTblVo getUsrParentUsrId() {
		return usrParentUsrId;
	}

	public void setUsrParentUsrId(UserMasterTblVo usrParentUsrId) {
		this.usrParentUsrId = usrParentUsrId;
	}

	public UserMasterTblVo getUsrConnectedUsrId() {
		return usrConnectedUsrId;
	}

	public void setUsrConnectedUsrId(UserMasterTblVo usrConnectedUsrId) {
		this.usrConnectedUsrId = usrConnectedUsrId;
	}

	public KnownusTblVO getiVOKNOWN_US_ID() {
		return iVOKNOWN_US_ID;
	}

	public void setiVOKNOWN_US_ID(KnownusTblVO iVOKNOWN_US_ID) {
		this.iVOKNOWN_US_ID = iVOKNOWN_US_ID;
	}
	

}
